LICTProject - Copy/LICTProject/Models/Project.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LICTProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ProjectMembers = new HashSet<ProjectMember>();
            this.OtherMembers = new HashSet<OtherMember>();
        }
    
        public int ProjectID { get; set; }
        public string Project_Title { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> StartTime { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> EndTime { get; set; }
        public string Duration { get; set; }
        public string Describe { get; set; }
        public string GrantProvider { get; set; }
        public string GrantAmt { get; set; }
        public string UniqueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherMember> OtherMembers { get; set; }
    }
}

LICTProject - Copy/LICTProject/Controllers/PersonnelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LICTProject.Models;

namespace LICTProject.Controllers
{
    public class PersonnelsController : Controller
    {
        private Entities db = new Entities();

       
        public ActionResult Index(string option, string search)
        {

            //if a user choose the radio button option as Subject  
            if (option == "FistName")
            {
                //Index action method will return a view with a student records based on what a user specify the value in textbox  
                return View(db.Personnels.Where(x => x.FirstName == search || search == null).ToList());
            }
            else if (option == "Title")
            {
                return View(db.Personnels.Where(x => x.Urls == search || search == null).ToList());
            }
            else
            {
                return View(db.Personnels.Where(x => x.LastName.StartsWith(search) || search == null).ToList());
            }
            //var personnels = db.Personnels.Include(p => p.LICT_Title1);
            //return View(personnels.ToList());
        }

        // GET: Personnels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personnel personnel = db.Personnels.Find(id);
            if (personnel == null)
            {
                return HttpNotFound();
            }
            return View(personnel);
        }

        // GET: Personnels/Create
        public ActionResult Create()
        {
            ViewBag.LICT_Title = new SelectList(db.LICT_Title, "Id", "Title");
            return View();
        }

        // POST: Personnels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Personnel personnel)
        {
            if (ModelState.IsValid)
            {
                personnel.Image = new byte[personnel.UploadImages.ContentLength];
                personnel.UploadImages.InputStream.Read(personnel.Image, 0, personnel.Image.Length);

                db.Personnels.Add(personnel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LICT_Title = new SelectList(db.LICT_Title, "Id", "Title", personnel.LICT_Title);
            return View(personnel);
        }

        // GET: Personnels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personnel personnel = db.Personnels.Find(id);
            if (personnel == null)
            {
                return HttpNotFound();
            }
            ViewBag.LICT_Title = new SelectList(db.LICT_Title, "Id", "Title", personnel.LICT_Title);
            return View(personnel);
        }

        // POST: Personnels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PersonnelID,FullName,Title,FirstName,LastName,LICT_Title,PostAtIOE,Email,PhoneNo,Urls,Image")] Personnel personnel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(personnel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LICT_Title = new SelectList(db.LICT_Title, "Id", "Title", personnel.LICT_Title);
            return View(personnel);
        }

        // GET: Personnels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Personnel personnel = db.Personnels.Find(id);
            if (personnel == null)
            {
                return HttpNotFound();
            }
            return View(personnel);
        }

        // POST: Personnels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Personnel personnel = db.Personnels.Find(id);
            db.Personnels.Remove(personnel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UserView()
        {
            var personnels = db.Personnels.Include(p => p.LICT_Title1);
          
            return View(personnels.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LICTProject - Copy/LICTProject/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LICTProject.Models;
using Newtonsoft.Json;
using System.IO;

namespace LICTProject.Controllers
{
    public class ProjectsController : Controller
    {
        private Entities db = new Entities();

       

        // GET: Projects
        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }
        public ActionResult UserView()
        {
            return View(db.Projects.ToList());
        }

        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.PersonnelID = new SelectList(db.Personnels, "PersonnelID", "FullName");        
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectID,Project_Title,StartTime,EndTime,Duration,Describe,GrantProvider,GrantAmt,UniqueId")] Project project)
        {
            if (ModelState.IsValid)
            {               
                db.Projects.Add(project);
                db.SaveChanges();
                //var connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Defaultconnection"].ConnectionString);
                //using (connection)
                //{
                //    SqlDataReader dr;
                //    connection.Open();
                //    string query = "SELECT * FROM dbo.TempData";
                //    SqlCommand com = new SqlCommand(query, connection);
                //    SqlCommand cmd = new SqlCommand("InsertData", connection);
                //    cmd.CommandType = CommandType.StoredProcedure;

                //    com.ExecuteNonQuery();
                //    dr = com.ExecuteReader();
                //    while (dr.Read())
                //    {
                //        cmd.Parameters.AddWithValue("@ProjectID", dr[1].ToString());
                //        cmd.Parameters.AddWithValue("@PersonnelID", dr[2].ToString());
                //        cmd.ExecuteNonQuery();
                //    }
                //    dr.Close();

                //}
                //connection.Close();
                ViewBag.PersonnelID = new SelectList(db.Personnels, "PersonnelID", "FullName");

                //return View();
                return RedirectToAction("Index");
            }

            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.PersonnelID = new SelectList(db.Personnels, "PersonnelID", "FullName");
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectID,Project_Title,StartTime,EndTime,Duration,Describe,GrantProvider,GrantAmt")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();

               
                return RedirectToAction("Index");
            }
            ViewBag.PersonnelID = new SelectList(db.Personnels, "PersonnelID", "FullName");
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        [HttpPost]
        public JsonResult SetProjectMember(string ProjectMemberJSON)
        {
            // ListMember members = JsonConvert.DeserializeObject<ListMember>(ProjectMemberJSON.ToString());
            Members[] members = JsonConvert.DeserializeObject<Members[]>(ProjectMemberJSON.ToString());
            
            var connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Defaultconnection"].ConnectionString);
            using (connection)
            {
                SqlDataReader dr;
                connection.Open();
                string query = "SELECT TOP 1 * FROM dbo.Project ORDER BY ProjectID DESC";
                SqlCommand com = new SqlCommand(query, connection);
                //com.Parameters.AddWithValue("@UniqueId", members[0].ProjectID);
                com.ExecuteNonQuery();
                dr = com.ExecuteReader();
                int ProjectID=0;
                while (dr.Read())
                {
                    if (dr[8].ToString().Equals(members[0].ProjectID))
                    {
                        ProjectID = Convert.ToInt32(dr[0]);                       
                    }
                    else
                    {
                        ProjectID = Convert.ToInt32(dr[0])+1;
                    }
                   
                                    
                }
                dr.Close();
               

                SqlCommand cmd = new SqlCommand("InsertData", connection);
                cmd.CommandType = CommandType.StoredProcedure;              
                cmd.Parameters.AddWithValue("@ProjectID", ProjectID);
                cmd.Parameters.AddWithValue("@PersonnelID", members[0].PersonnelID);
               
                cmd.ExecuteNonQuery();
              
            }
            connection.Close();
            return Json("Success");
        }

        [HttpPost]
        public JsonResult SetOtherMembers(string OtherMemberJSON)
        {
            // ListMember members = JsonConvert.DeserializeObject<ListMember>(ProjectMemberJSON.ToString());
            OtherMembers[] members = JsonConvert.DeserializeObject<OtherMembers[]>(OtherMemberJSON.ToString());

            var connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Defaultconnection"].ConnectionString);
            using (connection)
            {
                SqlDataReader dr;
                connection.Open();
                string query = "SELECT TOP 1 * FROM dbo.Project ORDER BY ProjectID DESC";
                SqlCommand com = new SqlCommand(query, connection);
                com.ExecuteNonQuery();
                dr = com.ExecuteReader();
                int ProjectID = 0;
                while (dr.Read())
                {
                    if (dr[8].ToString().Equals(members[0].ProjectID))
                    {
                        ProjectID = Convert.ToInt32(dr[0]);
                    }
                    else
                    {
                        ProjectID = Convert.ToInt32(dr[0])+1;
                    }

                }
                dr.Close();
               
                SqlCommand cmd = new SqlCommand("InsertOtherMember", connection);
                cmd.CommandType = CommandType.StoredProcedure;
               
                cmd.Parameters.AddWithValue("@ProjectID", ProjectID);
                cmd.Parameters.AddWithValue("@OtherMember", members[0].OtherMember);
               
                cmd.ExecuteNonQuery();
            }
            connection.Close();
            return Json("Success");
        }



        //for uniqueID validation// doesn't work i guess

        [HttpPost]
        public JsonResult DoesAlreadyExists(string UniqueID)
        {

            return Json(IsIdAvailable(UniqueID));

        }
        public bool IsIdAvailable(string UniqueID)
        {  
            List<Project> projects = new List<Project>();
            var ID = (from u in projects
                              where u.UniqueId.ToUpper() == UniqueID.ToUpper()
                              select new { UniqueID }).FirstOrDefault();

            bool status;
            if (ID != null)
            {

                //Already registered  
                status = false;
            }
            else
            {
                //Available to use  
                status = true;
            }


            return status;
        }

    }
}

LICTProject - Copy/LICTProject/Views/Projects/Delete.cshtml
@model LICTProject.Models.Project

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>
        @Html.DisplayFor(model => model.Project_Title)
    </h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StartTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Describe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Describe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GrantProvider)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GrantProvider)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GrantAmt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GrantAmt)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LICTProject - Copy/LICTProject/Views/Projects/Details.cshtml
@model LICTProject.Models.Project

@{
    ViewBag.Title = "Details";
    if (Request.IsAuthenticated)
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }


}

<link rel="stylesheet" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css">


<!-- Theme style -->
@*<link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">*@
<!--For Datatables-->
<link href="~/bower_components/datatables.net-bs/css/select.datatable.min.css" rel="stylesheet" />
<link rel="stylesheet" href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">


<h1 style="font-family:Serif"> @Html.DisplayFor(model => model.Project_Title)</h1>

<div class="box box-danger">
    <div class="box-body bg-gray">
        <div class="box-header" style="margin-top:0px">
            <p class="box-header" style="text-align: center; font-size:x-large; font-weight:bolder "><b>DETAILS</b></p>
        </div>
        <div class="col-md-12">
            <label class="col-md-offset-5" style="font-size:large; font-family:'Bodoni MT'"> @Html.DisplayNameFor(model => model.StartTime): </label>
            <label style="font-size:large; font-family:'Bodoni MT'; text-indent:60px"> @Html.DisplayFor(model => model.StartTime) </label>
        </div>

        <div class="col-md-12">
            <label class="col-md-offset-5" style="font-size:large; font-family:'Bodoni MT'"> @Html.DisplayNameFor(model => model.EndTime): </label>
            <label style="font-size:large; font-family:'Bodoni MT'; text-indent:65px"> @Html.DisplayFor(model => model.EndTime) </label>
        </div>


        <div class="col-md-12">
            <label class="col-md-offset-5" style="font-size:large; font-family:'Bodoni MT'"> @Html.DisplayNameFor(model => model.GrantProvider): </label>
            <label style="font-size:large; font-family:'Bodoni MT'; text-indent:30px"> @Html.DisplayFor(model => model.GrantProvider) </label>
        </div>

        <div class="col-md-12">
            <label class="col-md-offset-5" style="font-size:large; font-family:'Bodoni MT'"> @Html.DisplayNameFor(model => model.GrantAmt): </label>
            <label style="font-size:large; font-family:'Bodoni MT'; text-indent:60px"> @Html.DisplayFor(model => model.GrantAmt)$ </label>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-6">

                <div class="box box-danger">
                    <div class="box-body">
                        <table id="example1" class="row-border hover order-column">
                            <thead>
                                <tr>
                                    <th>
                                        Project Members:
                                    </th>

                                </tr>
                            </thead>

                            @foreach (var item in Model.ProjectMembers)
                            {
                                <tr>
                                    <td>
                                        <a href=" @Url.Action("Details", "Personnels", new { id = item.PersonnelID }) ">  @Html.DisplayFor(modelItem => item.Personnel.FullName)</a>
                                      
                                    </td>
                                </tr>
                            }

                        </table>
                    </div>
                </div>

            </div>
            <div class="col-md-6">

                <div class="box box-danger">
                    <div class="box-body">
                        <table id="example2" class="row-border hover order-column">
                            <thead>
                                <tr>
                                    <th>
                                        Other Members:
                                    </th>
                                </tr>
                            </thead>
                            @foreach (var item in Model.OtherMembers)
                            {
                                <tr>
                                    <td>
                                       
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
<div class="box box-danger">
    <div class="box-body bg-gray">
        <div class="box-header" style="margin-top:0px">
            <p class="box-header" style="text-align: center; font-size:x-large; font-weight:bolder "><b>Description</b></p>
        </div>
        <label style="font-size:large; font-weight:normal; font-family:'Times New Roman'; text-align:justify"> @Html.DisplayFor(model => model.Describe) </label>

    </div>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ProjectID }) |
    @Html.ActionLink("Back to List", "Index")

</p>

@section scripts{
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>


    <!-- DataTables -->
    <script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            var table = $('#example1').DataTable();
            var table = $('#example2').DataTable();
            //$('#example2').DataTable({
            //    'paging': true,
            //    'lengthChange': false,
            //    'searching': false,
            //    'ordering': true,
            //    'info': true,
            //    'autoWidth': false
            //})



            $('#example tbody').on('click', 'tr', function () {
                $(this).toggleClass('selected');
            });

            $('#example tbody').on('click', 'tr', function () {
                var data = table.row(this).data();
                alert('You clicked on ' + data[0] + '\'s row');
            });

        })
    </script>


}

LICTProject - Copy/LICTProject/Views/Projects/UserView.cshtml
@model IEnumerable<LICTProject.Models.Project>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--For Datatables-->
<link href="~/bower_components/datatables.net-bs/css/select.datatable.min.css" rel="stylesheet" />
<link rel="stylesheet" href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">


<div class="row" style="margin-left:5%; margin-right:5%">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">PROJECTs</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <table id="example1" class="row-border hover order-column">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Project_Title)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.StartTime)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EndTime)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.GrantProvider)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.GrantAmt)
                            </th>
                           
                        </tr>
                    </thead>


                    @foreach (var item in Model)
                    {
                        <tr>
                            <td  style="font-family:sans-serif; font-weight:bold">
                              
                                    <a style="font-weight:normal; align-content:flex-end" href="@Url.Action("Details", "Projects", new { id = item.ProjectID })"> @Html.DisplayFor(modelItem => item.Project_Title)</a>
           
                                
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.StartTime)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.EndTime)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.GrantProvider)
                            </td>
                            <td align="center">
                                @Html.DisplayFor(modelItem => item.GrantAmt)
                            </td>
                           
                        </tr>
                    }

                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- ./wrapper -->
<!-- jQuery 3 -->
@section scripts{
    <script src="/bower_components/jquery/dist/jquery.min.js"></script>


    <!-- DataTables -->
    <script src="/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="/dist/js/demo.js"></script>
    <!-- page script -->
    <script>
        $(function () {
            var table = $('#example1').DataTable();

            $('#example tbody').on('click', 'tr', function () {
                $(this).toggleClass('selected');
            });

            $('#example tbody').on('click', 'tr', function () {
                var data = table.row(this).data();
                alert('You clicked on ' + data[0] + '\'s row');
            });

        })
    </script>


}